import { cn } from "@/lib/utils"

import "./globals.css"

import { ClerkProvider } from "@clerk/nextjs"

import { fontMono, fontSans } from "@/lib/font"
import { Toaster } from "@/components/ui/toaster"
import { Providers } from "@/components/providers"
import { TailwindIndicator } from "@/components/tailwind-indicator"

export const metadata = {
  title: {
    default: "Create Next App",
    template: `%s - Create Next App`,
  },
  description: "Generated by create next app",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable,
            fontMono.variable
          )}
        >
          <Providers attribute="class" defaultTheme="system" enableSystem>
            {children}
            <TailwindIndicator />
          </Providers>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  )
}
